import { TerrainType } from "../../types/TerrainType.ts";

const ROW1 = new Map<number, TerrainType>([
  [0, "sea"],
  [1, "sea"],
  [2, "sea"],
  [3, "sea-stack"],
  [4, "sea"],
  [5, "sea"],
  [6, "sea"],
  [7, "sea"],
  [8, "sea"],
  [9, "sea"],
  [10, "sea-stack"],
  [12, "sea"],
  [13, "sea"],
  [14, "sea"],
  [15, "sea"],
  [16, "sea"],
  [17, "sea"],
  [18, "sea"],
  [19, "sea"],
  [20, "sea"],
  [21, "sea"],
  [22, "sea"],
  [23, "sea"],
  [24, "sea"],
  [25, "sea"],
  [26, "sea"],
  [27, "sea"],
  [28, "sea"],
  [29, "sea"],
  [30, "sea"],
  [31, "sea"],
]);

const ROW2 = new Map<number, TerrainType>([
  [0, "sea"],
  [1, "sea"],
  [2, "sea"],
  [3, "sea"],
  [4, "sea"],
  [5, "sea"],
  [6, "sea"],
  [7, "sea"],
  [8, "sea"],
  [9, "sea"],
  [10, "sea"],
  [12, "sea"],
  [13, "sea"],
  [14, "sea"],
  [15, "sea"],
  [16, "sea"],
  [17, "sea"],
  [18, "sea-stack"],
  [19, "sea"],
  [20, "sea"],
  [21, "sea"],
  [22, "sea-stack"],
  [23, "sea"],
  [24, "sea"],
  [25, "sea"],
  [26, "beach"],
  [27, "plain"],
  [28, "plain"],
  [29, "plain"],
  [30, "plain"],
  [31, "beach"],
]);

export const TERRITORY_REACHER = new Map([
  [
    0,
    ROW1,
  ],
  [
    1,
    ROW2,
  ],
]);
